server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false


    # add to servises
#    eureka:
#      instance:
#        prefer-ip-address: true
#      client:
#        serviceUrl:
#          defaultZone: http://localhost:8761/eureka/